### PR TITLE
Added MyHeritage provider

### PR DESCRIPTION
**Pull request by papinto**
this is a working provider for MyHeritage.com

### CODE REVIEW

**Comment by TerribleDev** [comment]
Thanks for the contribution I'll look it over in the next day or so and provide feedback. if its possible, can you squish the commits down to a single commit?

**Comment by papinto** [comment]
I'll look up how to squish them and do that (not done it before).

**Comment by papinto** [comment]
I tried squishing the commits but can't seem to get it to work.
Would it be easier if I just add the files to a new fork and make another pull request?

**Comment by TerribleDev** [comment]
don't worry about it...

**Pull request merged**
