### PR TITLE
Log exception when something goes wrong

### PR DESCRIPTION
**Pull request by kevfromireland**
Lots of details are lost when an exception occurs during login. We should log those so that we can determine which part of the method is throwing. 

I would also be keen to do a few method extracts as that one try block does a few different things, but not sure what your policy is on more substantial refactors?

### CODE REVIEW

**Comment by TerribleDev** [comment]
We do log to the owin log interface https://github.com/TerribleDev/OwinOAuthProviders/blob/master/src/Owin.Security.Providers.Bitbucket/BitbucketAuthenticationHandler.cs#L148

Any changes that we can agree on will be accepted. Size is of no concern, but regression testing such changes is, as the project is not well tested unfortunately

**Comment by kevfromireland** [comment]
The change in this PR affects only the Salesforce provider, and instead of logging just the `Message` property of the exception will instead pass the entire exception off to OWIN's logging so that things like the stack trace should be logged. 

Is it suitable for merging as-is?

**Comment by TerribleDev** [comment]
yes thats fine...

**Comment by kevfromireland** [comment]
Can we merge this one then? We're seeing issues in prod I'd like to have more info on.

**Comment by TerribleDev** [comment]
Sure gimme 20 minutes

**Comment by TerribleDev** [comment]
alright @kevfromireland its building/publishing now it will be 2.12.0 it should be published to nuget within the next 10 minutes, and then nuget has to index it (so maybe live in 30 minutes).

**Comment by TerribleDev** [comment]
@kevfromireland https://www.nuget.org/packages/Owin.Security.Providers.Salesforce/2.12.0

**Pull request merged**
