### PR TITLE
Add imgur provider

### PR DESCRIPTION
**Pull request by kappa7194**
Hello, I've added a provider for [imgur](https://imgur.com/). The implementation is complete and it works.

I know I haven't (yet) added the XML documentation to the code, I've submitted this pull request to get feedbacks on the implementation.

P.s. How would you like me to handle the two errors marked by TODOs in ImgurAuthenticationHandler (communication failure and response deserialization failure)? Should I throw an exception?

### CODE REVIEW

**Comment by jerriep** [comment]
Thanks for contribution. I have scheduled to look at this on Friday

**Comment by kappa7194** [comment]
If you could let me know how I should handle any exception thrown by the HttpClient and/or failure codes returned when dealing with the remote endpoint (I couldn't see a common behaviour in the existing providers) I'll have everything ready and shiny by Friday.

**Comment by jerriep** [comment]
Yeah if there is no common implementation, then I would say to just go ahead and implement it as you feel comfortable with.

**Comment by kappa7194** [comment]
I've committed some refactoring and the XML documentation.

Let me know if you find any issue.

**Comment by jerriep** [comment]
:+1:

**Comment by jerriep** [comment]
Thanks again @kappa7194 

I am waiting for feedback on another PR before I do a new release

**Comment by jerriep** [comment]
@kappa7194 We are looking for help moving to ASP.NET 5. Please read http://www.jerriepelser.com/blog/calling-contributors-for-oauth-providers

**Pull request merged**
