### PR TITLE
Basic Fitbit OAuth Provider Implementation

### PR DESCRIPTION
**Pull request by jmloeffler**
Created a new Fitbit provider based on the code from the github provider and altering it based on the Fitbit api docs.  There are some additions I'd like to make so that people can customize the permissions being requested, but I wanted to get this initial functionality submitted in case there are problems with my implementation in general.

Now that I somewhat know what I'm doing, is there any interest in a test-driven version or a set of composeable classes to reduce the repetition among the different provider implementations?

### CODE REVIEW

**Comment by jerriep** [comment]
@jmloeffler Thanks for the contribution. Can you please look at resolving the conflict that GH is complaining about?

**Comment by jmloeffler** [comment]
Sure thing. I think my fork repo just fell behind master when pull request #122 was merged.

**Comment by jmloeffler** [comment]
Sorry for the delay. I brought my fork up to date and that resolved the conflict.  Please let me know if you have any issues, criticisms, or desired changes.  Thanks.

**Comment by jerriep** [comment]
Thanks :) I have scheduled time to look at it on Friday

**Comment by jerriep** [comment]
Version 1.24 now on Nuget. Thanks!!

**Comment by jerriep** [comment]
@jmloeffler We are looking for help moving to ASP.NET 5. Please read http://www.jerriepelser.com/blog/calling-contributors-for-oauth-providers

**Comment by jmloeffler** [comment]
I'd love to help.  Thanks for pointing this out.  Count me in for the Fitbit provider, at the very least.

**Pull request merged**
