### PR TITLE
Implemented customizable profile fields for LinkedIn 

### PR DESCRIPTION
**Pull request by paullooijmans**
As specified in issue #43

I tried to minimize the amount of changes to make it easy to review. I thought about removing the UserInfoEndpoint private const because it's only used in one place and I didn't like making a variable with the same name. 

Let me know if you want me to change anything. Thanks!

### CODE REVIEW

**Comment by paullooijmans** [comment]
@jerriep just checking in to see if you need me to do anything else for this. Thanks!

**Comment by jerriep** [comment]
I am taking a bit of a break. Will try and look at it sometime over the next few weeks. Thanks :)

**Comment by paullooijmans** [comment]
OK good to know thanks. When you do get around to it and anything needs changing don't hesitate to contact me.

**Comment by paullooijmans** [comment]
Thanks @jerriep !

**Pull request merged**
