### PR TITLE
Add support for the prompt parameter in Salesforce

### PR DESCRIPTION
**Pull request by spencerthang**
As described, would be really useful to add a prompt parameter to force the user to re-authorize, especially if the user has multiple Salesforce logins.

### CODE REVIEW

**Comment by jerriep** [comment]
:+1: great stuff, thanks :)

**Comment by spencerthang** [comment]
@jerriep thanks for merging :)

Could there be a new release soon so my project can make use of these changes with the nuget package?

Cheers!

**Comment by jerriep** [comment]
Sure, I pushed new version (1.22.1) to Nuget for you

**Comment by spencerthang** [comment]
Thanks a bunch :)

**Pull request merged**
