### PR TITLE
POSTing to request an auth code

### PR DESCRIPTION
**Pull request by mstodd**
Rendering a form to be automatically POSTed instead of GETting auth URL

My GET was failing, I believe due to the length of the state parameter.  Instead of hacking the state param, a POST is now performed as per the linkedin documentation: https://developer.linkedin.com/docs/oauth2

### CODE REVIEW

**Comment by jerriep** [comment]
@mstodd: The link you provided does not state that POSTing to https://www.linkedin.com/uas/oauth2/authorization is working? Do you have a link where LinkedIn confirms that this is supported?

**Comment by mstodd** [comment]
Damn.  I'm questioning my sanity, but I want to say that it did say to
POST.  Even in their REST Console, they POST.  I'm going to ask if it
changed, or I was looking at a different version of the doc or something:

​

**Comment by jerriep** [comment]
Thanks, because even if it works now, if it is not explicitly supported they can easily yank it anytime they want :)

**Comment by jerriep** [comment]
I am going to close this PR without merging it. If documentation can be supplied that this a supported way to do it, then we can look at it again.

**Pull request closed without merging**
