### PR TITLE
twitch oauth works

### PR DESCRIPTION
**Pull request by TerribleDev**
Twitch oauth! #46

### CODE REVIEW

**Comment by TerribleDev** [comment]
Please go through this with a fine tooth comb, as I have never done oauth stuff before.

**Comment by jerriep** [comment]
@tparnell8 Thanks a lot for this! It may be a week or so before I have time to look at it though...

**Comment by TerribleDev** [comment]
@jerriep thats fine. It all seems to work I just mentioned it as an FYI.

**Comment by jerriep** [comment]
New version pushed to Nuget, thanks!

**Pull request merged**
