### PR TITLE
Strava Provider Implementation Only from strava-main

### PR DESCRIPTION
**Pull request by segilbert**
Please consider this pull request contribution for Strava OAuth Provider support to your fantastic project. Let me know.  I made the requested changes per your earlier review.  Thanks!

Cheers,
Sean

### CODE REVIEW

**Comment by jerriep** [comment]
Hi @segilbert can you please explain to me which is the correct PR I should use? This one, or the other one you submitted before? What is the difference between the two?

**Comment by segilbert** [comment]
You asked me to break the original PR #111 into 2 (#112, #113) requests to better segregate the changes.  PR #112 contains just the Key Storage and ReadMe.md changes.  PR #113 contains the Strava Provider implementation + changes for code review comments on #111.  I think PR #111 can be removed.

Sean

**Comment by jerriep** [comment]
Huh? I never asked you to split the PR.....

In any case, now that I know what is happening I will close the old PR and merge the other 2. It will have to wait until Friday though...

**Comment by jerriep** [comment]
Hi @segilbert the file changes for your PR for the key storage has leaked into this PR, and I am not quite sure I want to accept those changes.

Your Key Storage implementation does not make sense to me. The file is still checked into source control so the developer can still accidentally check in their secrets. 

Your explanation in the readme.md about ignoring local changes is something I can promise you that most developers looking to contribute to this repo is not going to look at.

In my mind checking in a app key and secret by mistake is not the end of the world. I have done it a few times for this repo as well. Simply just delete the app in the relevant service or reset the keys in that service.

I would like to hear your feedback for the rationale behind splitting it out. And yes, I understand that you should do something like that in a proper system, but in this case I have to weigh it against the barrier it puts up for other developers making contributions.

**Comment by segilbert** [comment]
I agree with your assessment. Interestingly enough ASPNET coming release addresses exact concern.  ASPNET coming release attempts to provide a solution to prevent developer from checking in OAuth and connection strings into version controls systems using DNX Secret Configuration.

https://github.com/aspnet/Home/wiki/DNX-Secret-Configuration

**Comment by jerriep** [comment]
@segilbert Can you please advise what is happening with this? Can you please clean out the storage of the keys from your commits as I cannot accept your PR in its current state.

Thank you

**Comment by jerriep** [comment]
Closing as there is no response from @segilbert

**Pull request closed without merging**
