### PR TITLE
add contributor

### PR DESCRIPTION
**Pull request by TerribleDev**
Think I can be added? I wrote the twitch oauth, helped with the Untappd oauth, and just submitted a PR for DeviantArt

### CODE REVIEW

**Comment by jerriep** [comment]
Of course you can. Thank you Tommy. 

I sort of leave it for contributors to go and add themselves, and every once in a while I will make sure it is updated...

**Comment by rodkings** [comment]
I helped @tparnell8  with the Untappd oauth, not too much to be added right?

**Comment by TerribleDev** [comment]
@rodkings I would guess you will probably want to submit a pull request listing yourself.

**Comment by rodkings** [comment]
@tparnell8  ty, I will do it.

**Pull request merged**
