### PR TITLE
Add new provider DoYouBuzz

### PR DESCRIPTION
**Pull request by D4rkTiger**
Add new french provider DoYouBuzz, a website which hosts CVs

### CODE REVIEW

**Comment by D4rkTiger** [comment]
That is the new one you already seen the folder in my previous pull request :-).

**Comment by D4rkTiger** [comment]
I have created another project related to yours.

[OwinOAuthProvidersConfig](https://github.com/D4rkTiger/OwinOAuthProvidersConfig)

**Comment by jerriep** [comment]
Thank you @D4rkTiger !

I cannot quite figure out what the other project you mentioned is about. Can you explain the Use Case to me?

**Comment by D4rkTiger** [comment]
It is a project that allows you to store in your web.config your API keys simpler than static in code thanks to a custom configuration section called "owinConfig".

**Comment by D4rkTiger** [comment]
It is already published as NuGet package if you want.

https://www.nuget.org/packages/Owin.Security.Providers.Config/

**Comment by jerriep** [comment]
Lately I actually make very little use of the OwinOAuthProviders project myself :)

You may also want to include a sample project, or documentation showing people how to use it.

**Pull request merged**
