### PR TITLE
Overrides ExpectContinue for LinkedIn HTTP API requests

### PR DESCRIPTION
**Pull request by jlcj1974**

### CODE REVIEW

**Comment by AlexArchive** [comment]
Works well on localhost. I am just waiting to hear back from Poul [here](https://github.com/RockstarLabs/OwinOAuthProviders/issues/87#issuecomment-90670608) re. deployment.

**Comment by pksorensen** [comment]
Looks good to me.

**Comment by aaron-horst** [comment]
Looks good to me also, adding 

  httpClient.DefaultRequestHeaders.ExpectContinue = false;

To my branch earlier to support a mission critical application reveals success after deployment as well.

**Comment by AlexArchive** [comment]
I merged this into a new branch [`LinkedIn-Fix`](https://github.com/RockstarLabs/OwinOAuthProviders/tree/LinkedIn-Fix) and published an [updated package](https://www.nuget.org/packages/Owin.Security.Providers/1.17.0-pre).

Please continue the discussion [here](https://github.com/RockstarLabs/OwinOAuthProviders/issues/87). 

I am so sorry @jlcj1974, I forgot to thank you - thank you :smile:!

**Comment by jlcj1974** [comment]
Glad we could get past this issue and get our users back online!  Hopefully, LinkedIn will acknowledge/address soon.

**Pull request closed without merging**
