### PR TITLE
adding spotify access token to the claims

### PR DESCRIPTION
**Pull request by samwa**
Hi
I need to do this for the spotify owin privider so I could then use the access token in my app
thought you might like to include it in the source (then I can switch back the using the nuget package again (hint hint)

### CODE REVIEW

**Comment by jerriep** [comment]
Hi @samwa do not understand why need it added as a claim seeing as you can access it from the Authenticated context. Can you please outline your use case for me?

**Comment by samwa** [comment]
maybe I'm not understanding how Owin works just yet. I thought that there might be a more sensible way of doing it!
basically, when the user is passed back to ExternalLoginCallback I need to know what the access token that Spotify has generated is so I can then create a playlist on their behalf

**Comment by jerriep** [comment]
See this blog post I wrote before:
http://www.jerriepelser.com/blog/get-the-twitter-profile-image-using-the-asp-net-identity

It shows how to take the access token from the Authenticated context, and add it as a claim so you can then access it in your AccountController to do with it whatever you want.

You can also look at this YouTube video I did showing the same technique:
https://www.youtube.com/watch?v=aTEkY_E6mV8

Will that work for you?

**Comment by samwa** [comment]
That's perfect, thanks for your help

**Pull request closed without merging**
