### PR TITLE
Added authentication provider for EVEOnline

### PR DESCRIPTION
**Pull request by mariozski**
Added authentication middleware according to specs - https://developers.eveonline.com/resource/single-sign-on

### CODE REVIEW

**Comment by AlexArchive** [comment]
Hi @mariozski. Many thanks for your contribution :smile:. 

I want to let you know that @jerriep recently put me in charge of this repository. I will carefully review and test these changes soon.

**Comment by AlexArchive** [comment]
I am sorry but I cannot manually test this because I cannot create my own credentials. When I go to the [applications](https://developers.eveonline.com/applications) page to register an application, I am told "developer registration requires that you have paid at least once". 

Would it be at all possible for you to provide a `clientId` and `clientSecret` so I can test this out locally? You'll need to set the redirect link to `http://localhost:1729/signin-eveonline`. You can email me at byteblast@gmail.com or comment here.

I hope we can work together to make this happen :bear:.

**Comment by mariozski** [comment]
Hey, no problem. I've just send you email with client id and secret. Let me know if you would have any problems. :-)

**Comment by AlexArchive** [comment]
I got it. Thank you. 

I have been doing some testing and things look good so far - good work. I noticed some discrepancies in your code - mostly formatting - but I will fix those for you. 

I am going to go unwind then sleep. Please do not remove the credentials you gave me as I want to do some more testing tomorrow.

Thanks again @mariozski.

**Comment by mariozski** [comment]
Sure, thanks as well for your time and testing.

**Comment by AlexArchive** [comment]
Looks good to me. 

I made some formatting changes to your branch and created a new pull request (#61) for @jerriep to review if he has time. 

I will keep this pull request open in case we notice any issues. I can retrofit any changes you make here into the `eveonline` branch I made if needed (hopefully not!)

**Comment by AlexArchive** [comment]
Merged!

**Comment by AlexArchive** [comment]
Awesome work @mariozski. I will publish an updated NuGet package shortly.

**Comment by AlexArchive** [comment]
Your changes are now live in version 1.15: https://www.nuget.org/packages/Owin.Security.Providers/1.15.0

**Comment by mariozski** [comment]
Thanks! :+1:

**Comment by jerriep** [comment]
@mariozski We are looking for help moving to ASP.NET 5. Please read http://www.jerriepelser.com/blog/calling-contributors-for-oauth-providers

**Pull request merged**
