### PR TITLE
massive change to the solution

### PR DESCRIPTION
**Pull request by Eonasdan**
Broke apart all of the providers into their own projects. This allows for each provider to be packed into their own dlls and thus into their own nuget packages. Each project has a post-build event that if in Release mode will take the assembly version and attempt to pack the dll into the appropriate nuget package.

### CODE REVIEW

**Comment by TerribleDev** [comment]
@Eonasdan can you please put all the projects in a folder called src so they are not polluting the root...something like

```
src/
  Owin.Security.Providers.VisualStudio
  Owin.Security.Providers.Vemo
  ...

``
```

**Comment by TerribleDev** [comment]
also can 7318fae82f42b54b2bbdcaf0a6548073b2c67a31 be a separate pull request since it is a separate bug/issue than this

**Comment by Eonasdan** [comment]
I've done the move. I left the demo project in root since it's not really "source". 

I'd have to temporarily undo my github patch so it could be a new PR if you want the separate.

**Comment by TerribleDev** [comment]
I will take a look at it later tonight thank you

**Comment by TerribleDev** [comment]
@Eonasdan none of the projects compile for me....

Many of the providers like Yammer, GooglePlus, HealthGraph, Paypal, etc. Are straight up missing both code and csproj files......

**Comment by Eonasdan** [comment]
wow.. sorry about that. My last commit was missing like 409 files! Double checked, solution builds for me. Try again?

**Comment by TerribleDev** [comment]
Appveyor says otherwise, and my machine concurs

**Comment by TerribleDev** [comment]
Are you sure the path to the nuget dll references is setup properly

**Comment by Eonasdan** [comment]
There! Sorry about all that.  It was building just fine for me. So I downloaded the repo again into a new directory and finally spotted the problem.

Also added a local nuget and changed the post build events to use that instead.

**Comment by TerribleDev** [comment]
sweet I'll take a peek...

**Comment by TerribleDev** [comment]
Nice work...I'm not in love with the fact that it still has that github change in it, but I'll take it...I don't think its too dangerous.

Breaking these packages out is both very helpful, and not simple so thank you for that!

I'll plan on publishing to nuget later this week after some testing...

**Comment by Eonasdan** [comment]
Sweet!

I didn't do a lot of testing since I only have need of the github package at the moment. So I'm happy to help fix anything I broke.

I pulled the OpenId into OpenIdBase so that OpenId, Steam and one other that escapes me at the moment could depend on OpenIdBase since they all used the same classes.

I'm not happy with having a duplicate Resource file in each project, but couldn't decide how I could be happy with that and make it work.

Due note that the nuget auto pack in the post-build event uses the Assembly Version to decide what version of the package should be.

**Comment by TerribleDev** [comment]
I plan on generating nuspec files dynamically during a build, so we don't have to maintain individual specs. I plan on publishing this over the weekend.

**Pull request merged**
