### PR TITLE
ArcGIS Portal provider

### PR DESCRIPTION
**Pull request by gavinharriss**
Adds an OAuth provider to support ArcGIS Portal product for enterprises. Almost identical to ArcGIS Online solution but adds support for:

- Specifying the host location where ArcGIS Portal is installed.
- Naming the authentication provider so more than one can be used side-by-side to support multiple ArcGIS Portal installations.

Originally attempted to inherit from ArcGIS Online provider, but a fair amount of refactoring is required to allow inheritance for everything that needs changing. To be revisited when time allows.

### CODE REVIEW

**Comment by vtforester** [comment]
I had a need to authenticate against Portal as well but was able to successfully accomplish this by just specifying the correct endpoints like so (in my Startup.Auth.cs file):

```csharp
var oAuthServer = ConfigurationManager.AppSettings["oAuthServer"];
// this is my portal url; something like: https://myserver.com/arcgis
if (!oAuthServer.EndsWith("/"))
    oAuthServer += "/";
app.UseArcGISOnlineAuthentication(new ArcGISOnlineAuthenticationOptions() {
    ClientId = ConfigurationManager.AppSettings["clientId"],
    ClientSecret = ConfigurationManager.AppSettings["clientSecret"],
    Endpoints = new ArcGISOnlineAuthenticationOptions.ArcGISOnlineAuthenticationEndpoints
    {
        AuthorizationEndpoint = oAuthServer + "sharing/rest/oauth2/authorize",
        TokenEndpoint = oAuthServer + "sharing/rest/oauth2/token",
        UserInfoEndpoint = oAuthServer + "sharing/rest/community/self"
    },
    Provider = new ArcGISOnlineAuthenticationProvider()
    {
        OnAuthenticated = context =>
        {
            context.Identity.AddClaim(new Claim("urn:ArcGISOnline:accessToken", context.AccessToken));
            context.Identity.AddClaim(new Claim("urn:ArcGISOnline:refreshToken", context.RefreshToken));
            return Task.FromResult<ArcGISOnlineAuthenticatedContext>(context);
        }
    }
});
```

This works perfectly except that the `Link` property that is set in **ArcGISOnlineAuthenticatedContext** uses a hard-coded 'https://www.arcgis.com/sharing/rest/community/users/' instead of the user endpoint that you specify.

**Comment by gavinharriss** [comment]
@vtforester Would you by chance have any pointers / examples on how to then use the authorization client-side in the ArcGIS JavaScript API? I seem to be hitting a block on that front at present.

I see you're adding an urn:ArcGISOnline:accessToken & urn:ArcGISOnline:refreshToken as additional claims. I assume this is to use them client-side somehow?

**Comment by vtforester** [comment]
In a nutshell, I append a cookie to all outgoing requests with the token, userId, expiration, etc.

```cs
var json = JsonConvert.SerializeObject(new
{
    userId = userClaim.Value,
    token = tokenClaim.Value,
    server = ConfigurationManager.AppSettings["oAuthServer"],
    expires = DateTime.Now.AddSeconds(1).Ticks,
    ssl = false
});
cookie.Value = json;
filterContext.HttpContext.Response.AppendCookie(cookie);     
```

Then I parse that cookie in JavaScript and set the `sessionStorage` (or `localStorage`) item that the ESRI JSAPI is looking for:

```javascript
define([
    'source/config/app-config',
    'esri/IdentityManager',
    'dojo/cookie'
], function (
    config,
    esriId,
    cookie
) {
        // grab oauth token from ASP.NET cookie and set the ESRI session item
        // this will allow the esriIdentity utilities to 
        // automatically register as a signed-in user
        var oauth = cookie('aspnet_oauth');
        if (oauth && Modernizr.sessionstorage) {
            oauth = JSON.parse(oauth);
            var identity = {};
            var portal = {};
            portal[oauth.server] = {
                token: oauth.token,
                userId: oauth.userId,
                ssl: oauth.ssl,
                expires: oauth.expires
            };
            identity[config.oAuthInfos[0].authNamespace] = portal;
        }
        sessionStorage.setItem('esriJSAPIOAuth', JSON.stringify(identity));
        // register oAuth infos here
        esriId.registerOAuthInfos(oAuthInfos);

        // then check sign in status
        esriId.checkSignInStatus(oAuthInfos[0].portalUrl);
        
        // finally, request the main entry point
        require(['source/main']);
    });
```

**Comment by gavinharriss** [comment]
@vtforester Thanks for the info, much appreciated! Setting the esriJSAPIOAuth storage item directly... explains why I didn't find anything usable scouring the ArcGIS API's.

**Comment by TerribleDev** [comment]
@gavinharriss can you make the build pass?

**Comment by gavinharriss** [comment]
I was a bit surprised the build failed as no new dependencies were introduced and is basically the same as Owin.Security.Providers.ArcGISOnline with a few tweaks.

I try and have a look soon to see if I can figure out why the build service has issues with it.

**Comment by gavinharriss** [comment]
Ok, all fixed - was some broken NuGet references. Paths were wrong.

**Comment by TerribleDev** [comment]
@gavinharriss hey sorry I forgot all about this...

**Pull request merged**
