### PR TITLE
ORCID auth

### PR DESCRIPTION
**Pull request by RickZee**
Added authentication provider for ORCID (see http://orcid.org/)

### CODE REVIEW

**Comment by RickZee** [comment]
Hi @tparnell8 

Would you be able to merge this provider into master? ORCID is ready to post it on their website! :)

**Comment by TerribleDev** [comment]
Sure can you update this PR

You need to fix the merge conflicts, and if you notice the project structure has recently changed. You will need to update this implementation to the new model.

**Comment by RickZee** [comment]
Hi @tparnell8,

Got it! Will do and let you know.

**Comment by TerribleDev** [comment]
Thanks, essentially each provider is its own package now...it shouldn't be too much work to implement the changes. 

Let me know if you need any help...

This model is new to this project, and I plan to release the first version(s) within the next 24 hrs or so...

I guess I should also give @Eonasdan a heads up about that :wink:

**Comment by TerribleDev** [comment]
@RickZee if you have time at some point you should also consider porting this to .net core, the new project model, and aspnet core 1.0 There is a project underway here: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers

**Comment by RickZee** [comment]
@tparnell8 - yes, I think I should contribute the to aspnet core as well, thanks for the suggestion!

**Comment by RickZee** [comment]
I will create another PR. I re-forked the repo due to the structure change.

**Comment by TerribleDev** [comment]
:+1:

**Pull request closed without merging**
