### PR TITLE
ORCID authentication provider

### PR DESCRIPTION
**Pull request by RickZee**
Hi @tparnell8, please see ORCID provider added to the new solution structure. No sure why it can't automatically merge though.

### CODE REVIEW

**Comment by TerribleDev** [comment]
I'll have some time to look at this in a day or two

**Comment by TerribleDev** [comment]
ok sorry I havn't gotten to this...life has been busy...I plan on looking at this asap..

**Comment by RickZee** [comment]
No problem! I know how life could be :)

**Comment by TerribleDev** [comment]
https://www.nuget.org/packages/Owin.Security.Providers.Orcid/

**Comment by TerribleDev** [comment]
it wouldn't build because you had a merge conflict, but I fixed it...

**Comment by RickZee** [comment]
Great! Thank you very much Tommy! I'll let orcid.org know about this release.

**Pull request merged**
