### PR TITLE
Adding wargaming.net openid login

### PR DESCRIPTION
**Pull request by Lorac**
I think there is only one thing to add, it would the different region.
For now it only supports NA login. If anyone know how to support multiple region login don't hesitate to modify the code accordingly.

### CODE REVIEW

**Comment by jerriep** [comment]
Developer documentation at:
https://eu.wargaming.net/developers/documentation/guide/getting-started/

**Comment by Lorac** [comment]
Yes, I know about all that documentation, I do have not much time right now to work on it. If I can I'll try push a fix this weekend.

**Comment by jerriep** [comment]
Sorry, was not meant for you @Lorac  :)

Was just a note for myself so when I come back to test this tomorrow morning, or write the documentation for http://www.oauthforaspnet.com/, that I know where to go to look at the docs and find where to register an app...

**Comment by jerriep** [comment]
Thanks @Lorac ! I added support for regions as well

**Comment by jerriep** [comment]
@Lorac We are looking for help moving to ASP.NET 5. Please read http://www.jerriepelser.com/blog/calling-contributors-for-oauth-providers

Although in your case the more appropriate repo will be https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers

**Pull request merged**
