### PR TITLE
Added UsePayPalAuthentication 

### PR DESCRIPTION
**Pull request by qanuj**
Added UserPayPalAuthentication for Issue #80

### CODE REVIEW

**Comment by jerriep** [comment]
@qanuj Were you able to test this? I configure a Sandbox account, but when PayPal redirects me to the login screen it won't log me in. I tried both my normal credentials, as well as the Sandbox email address which PayPal supplied to be (along with my normal password), but no luck.

Any tips would be appreciated. 

I cannot accept PR until I can test properly

**Comment by qanuj** [comment]
@jerriep PayPal is pain for app creation, you might need to re-create app, and use the application key and id, otherwise, it just takes the first request, fails every time.

**Comment by jerriep** [comment]
Not sure I understand. Should I use the application key and id for the username and password?

**Comment by qanuj** [comment]
this is reference point for the problem I have faced. https://medium.com/@bartriepe/log-in-with-paypal-a-fractal-of-bad-design-58ce19939a9d 

You should be using your sandbox account details.
and do need to create PayPal Application and use the applicationKey and secret in  

`OwinOAuthProvidersDemo/App_Start/Startup.Auth.cs`

also need to make sure you have permissions checked when creating application in PayPal.

**Comment by jerriep** [comment]
Ok, in the sandbox Paypal gives me a Sandbox account - in my case it is `jerrie-facilitator@jerriepelser.com`. What password do I use with that? The same password as for my normal Paypal email address?

**Comment by qanuj** [comment]
No, it should be different password then that. you can reset passwords for these account on developer dashboard.

**Comment by jerriep** [comment]
Aaah, OK great. Things are now starting to make sense. I see the accounts section and will go and set the password for that account over there. 

Thanks for the patience @qanuj :)

It is because of these silly little nuances that I created http://www.oauthforaspnet.com/ :) Will document it there once I am done

**Comment by qanuj** [comment]
Nice work on http://www.oauthforaspnet.com/

**Comment by jerriep** [comment]
Great stuff, thanks @qanuj

**Comment by qanuj** [comment]
Awesome !

**Comment by jerriep** [comment]
@qanuj We are looking for help moving to ASP.NET 5. Please read http://www.jerriepelser.com/blog/calling-contributors-for-oauth-providers

**Pull request merged**
